[build]
  command = "npm install --no-optional --no-audit --no-fund && node prebuild.js && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22"
  NODE_OPTIONS = "--max-old-space-size=4096"
  NEXT_TELEMETRY_DISABLED = "1"
  NPM_CONFIG_PROGRESS = "false"
  NPM_CONFIG_LOGLEVEL = "error"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 