[build]
  command = "npm install --no-optional --no-audit --no-fund && node prebuild.js && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22"
  NODE_OPTIONS = "--max-old-space-size=4096"
  NEXT_TELEMETRY_DISABLED = "1"
  NPM_CONFIG_PROGRESS = "false"
  NPM_CONFIG_LOGLEVEL = "error"
  # Disable Netlify secrets scanning for this project (or use omit paths)
  SECRETS_SCAN_ENABLED = "false"
  # Additionally omit Next.js build output from scans to avoid false positives
  SECRETS_SCAN_OMIT_PATHS = ".next/**"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 