[phases.setup]
nixPkgs = ["nodejs-18_x", "ffmpeg", "fontconfig", "dejavu_fonts"]

[phases.install]
cmds = [
    "cp railway-package.json package.json",
    "npm install --omit=dev"
]

[phases.build]
cmds = [
    "node -e \"const esbuild=require('esbuild'); esbuild.build({entryPoints:['src/lib/video-generator/efficient-generator.ts'], bundle:true, platform:'node', format:'cjs', outfile:'dist/efficient-generator.js', sourcemap:false}).catch(e=>{console.error(e); process.exit(1);})\""
]

[start]
cmd = "node railway-backend.js"

[variables]
NODE_ENV = "production" 