[phases.setup]
nixPkgs = ["nodejs-18_x", "ffmpeg", "fontconfig", "dejavu_fonts"]

[phases.install]
cmds = [
    "cp railway-package.json package.json",
    "npm install --omit=dev"
]

[phases.build]
cmds = []

[start]
cmd = "node railway-backend.js"

[variables]
NODE_ENV = "production" 