[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = [
    "cp railway-package.json package.json",
    "npm ci"
]

[start]
cmd = "npm run start:railway"

[variables]
NODE_ENV = "production" 