[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = [
    "cp railway-package.json package.json",
    "npm install --omit=dev"
]

[start]
cmd = "node test-railway.js"

[variables]
NODE_ENV = "production" 