[phases.setup]
nixPkgs = ["nodejs-18_x", "python3", "python3Packages.pip", "ffmpeg", "pkg-config"]

[phases.install]
cmds = [
    "npm ci",
    "pip install -r requirements.txt"
]

[start]
cmd = "npm run start:railway"

[variables]
NODE_ENV = "production" 